### PR TITLE
Update image and Helm chart references for API Gateway `v0.1.0`

### PR DESCRIPTION
**Pull request by nathancoleman**
As part of GA release for Consul API Gateway, update the learn resources to use the correct image and Helm chart refs.

### CODE REVIEW

**Review by mikemorris — APPROVED** [review]
LGTM pending actual release availability, noting that this repo will need a git tag after merge per the updated refs in https://github.com/hashicorp/learn/pull/4440 @eddie-rowe

**Comment by nathancoleman** [comment]
@eddie-rowe would you mind reviewing this when you get a moment?

**Comment by eddie-rowe** [comment]
Overall, LGTM. 

Instead of merging this branch from your forked repo, I created a new branch with your changes (as well as some additional changes in line with the tutorial update). I also added you as a reviewer on the tutorial update so you can test the complete workflow.

Learn-Consul-Kubernetes Update PR: https://github.com/hashicorp/learn-consul-kubernetes/pull/49
Learn Guide Update PR: https://github.com/hashicorp/tutorials/pull/96

This PR can be closed once all changes are validated on these two ^

**Comment by nathancoleman** [comment]
Closing in favor of #49

**Pull request closed without merging**
